version: 2

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
  system_packages: true # can contain TF and more packages

sphinx:
  builder: html
  configuration: docs/conf.py
#  fail_on_warning: true
