# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on: [push]

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -e .[test]
          pip install coverage
      - name: Download test data
        run: python data/download_test_files.py > /dev/null
      - name: Run pytest-cov
        run: coverage run -m pytest --basetemp={envtmpdir}
      - name: Create XML report
        run: coverage xml
      - uses: codecov/codecov-action@v2.0.3
        with:
          file: ./coverage.xml

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-feature=2020-resolver -e .[dev]
      - name: Download test data
        run: python data/download_test_files.py > /dev/null
      - name: Test with pytest
        run: PHASESPACE_EAGER=0 pytest --basetemp={envtmpdir}
      - name: Test with pytest (eager mode)
        run: PHASESPACE_EAGER=1 pytest --basetemp={envtmpdir}
      - name: Test with pytest (NumPy backend)
        run: PHASESPACE_BACKEND=NUMPY pytest --basetemp={envtmpdir}
